### ISSUE TITLE
Problem with anime and checking if it's cached on a debrid service

### ISSUE THREAD

**Issue by MadMax96xaMdaM** [wako-unofficial-addons/helios#10]
When I try to scrape an anime episode, in my experience, it never shows as cached even if it is. I tried this with different anime. I checked if they're actually cached by just adding them to RD and they showed as done immediately which leads me to think that they were already cached and the checking mechanism might have a problem.

**Comment by davidreedmichigan** [comment]
Could you please provide me example of some anime (with the right episode) to test it

**Comment by MadMax96xaMdaM** [comment]
It seems to have been fixed.
