### ISSUE TITLE
Source Filtering

### ISSUE THREAD

**Issue by orionoidx** [wako-unofficial-addons/helios#11]
I'm writing a custom provider for Helios, but often 80% or more of the links returned by the site are removed. For some episodes Helios removes all links for an unknown reason. I've checked the torrent attributes and they seem to be all OK (filesize, seeds and peers greater than 0, file name contains the title and year/episodeCode).

I've played around with the torrent attributes and there seems to be some strange behavior. For instance, if you increase the seeds of a torrent that has eg 10 seeds by a few, then suddenly it shows up in Wako's list. I thought that it might remove torrents with only a few seeds, but then Wako shows torrents that only have 1 or 2 seeds.

Could you provide more details on how and what is exactly filtered?

And would it be possible to add a new attribute to the provider JSON that allows to switch off filtering completely for that provider? Something like:

`"filtering" : false`

**Comment by orionoidx** [comment]
I've also noticed that the results between these two queries differs. For the first one I don't get any results in Wako, for the second one I do.

```
"episode":
{
	"query": "/api?q={query}",
	"keywords": "{title} {year} {episodeCode}"
},
```

```
"episode":
{
	"query": "/api?q={title} {year} {episodeCode}",
	"keywords": ""
},
```

I think the problem is with adding the year to the keywords. Does that maybe mean that Wako filters out all file names that do not contain the keywords (in this case the year)? I want to add the year, because there are some shows with the same name.

I also noticed that the IMDb ID only works for movies and not episodes. Any reason why one cannot search episodes by IMDb ID? Would be nice to search by a show's IMDb with the season/episode number.

**Comment by davidreedmichigan** [comment]
Hi, 
Sorry for the late answer.
I currently creating Helios 2 to make things a lot more clearer (in the code and for the end user).
Source are filtered by seeds, seeds with 0 are removed if not cached: https://github.com/wako-unofficial-addons/helios/blob/master/projects/plugin/src/plugin/queries/torrents/torrent-from-providers.query.ts#L633

ImdbId should be replace not matters if episode or movie

Do you test your provider by running Helios Project on your browser or only on wako?

**Comment by orionoidx** [comment]
All torrents have at least 1 seed, but they are still removed. I see your code says

`torrent.seeds > 1`

Shouldn't that rather be:

`torrent.seeds >= 1`

And what do you mean by "ImdbId should be replace"?
Only tested Helios in Wako. How do you run this in a browser without Wako?

**Comment by orionoidx** [comment]
Never mind, Figured out the node/angular story in the browser. Will make debugging a lot easier.

Just did a test with IMDB ID for an episode. And in Helios the ID is "undefined" for episode. For movies it is fine. So IMDB are maybe not detected for episodes?

**Comment by davidreedmichigan** [comment]
Gonna look at it. In next version it will be for sure ;)

**Comment by orionoidx** [comment]
Sorry man for spamming your bug tracker. While debugging your code, these are some bugs and/or suggestions.

1. Change minimum torrent seeds from "> 1" to ">= 1". [Code here](https://github.com/wako-unofficial-addons/helios/blob/master/projects/plugin/src/plugin/queries/torrents/torrent-from-providers.query.ts#L633)
2. IMDb ID for episodes does not work, it is undefined. IMDb ID currently only works for movies.
3. Add an attribute to the provider JSON that disables file name filtering on a per-provider basis. [Code here](https://github.com/wako-unofficial-addons/helios/blob/master/projects/plugin/src/plugin/queries/torrents/torrent-from-providers.query.ts#L556)
4. Add an attribute to the provider JSON that allows one to set a custom timeout for requests. Currently it is hardcoded at 10s, which is not enough for some slower sites and/or some slower internet connections for some users. [Code here](https://github.com/wako-unofficial-addons/helios/blob/master/projects/plugin/src/plugin/queries/torrents/torrent-from-provider.query.ts#L328)

**Comment by davidreedmichigan** [comment]
Have a look at branch@2.0.0 https://github.com/wako-unofficial-addons/helios/tree/2.0.0.

1. There is no filter on seeds anymore
2. Should be set
3. No filter anymore
4. Not implemented, but easy to do so
