### ISSUE TITLE
Optimize the open menu

### ISSUE THREAD

**Issue by tele-grams** [wako-unofficial-addons/helios#13]
Moving the issue from https://github.com/wako-app/wako/issues/57

Looks like you can optimize the menu (the menu where we have, open in Kodi, Open in VLC etc) once we get the link to play:

    Remove "Copy URL", as "Share URL" will also has "copy URL" or "copy to clipboard"

    Replace "Open with VLC" with "Open with" or "Play with" to list all apps which can play Media (Be it VLC/MX or any other players in the system) on the local system.

In TTV based apps "open with" or "Play with" lists all Media players + also lists all downloaders on the device, with which we can download the media as well if one wants to (I have never done it though).

With these we have covered everything.
point_up This is what I get when I click on "Play with" or "Open with" on TTV based apps, it lists:

    All media players locally (MX, Kodi, Podcast addict)
    Yatse players (+ Hosts created on Yatse, the middle row)
    Downloaders from ES explorer/file explorers

This would cover it all, please check if you could make these changes:

    Remove "Copy URL", as "Share URL" will also has "copy URL" or "copy to clipboard"
    Replace "Open with VLC" with "Open with" or "Play with" to list all apps which can play Media (Be it VLC/MX or any other players in the system) on the local system

**Comment by davidreedmichigan** [comment]
Need this https://github.com/wako-app/wako/issues/65 to be added for point 2
