### ISSUE TITLE
GET RD error while searching for sources

### ISSUE THREAD

**Issue by basalona** [wako-unofficial-addons/helios#17]
I am consistently getting Uncaught error 503 when calling POST - https://api.eal-drbrid.com/rest/1.0/unrestrict/link

**Comment by davidreedmichigan** [comment]
Hi,
Could you tell me which show/movie you are trying to watch? and which source you are selecting.
thx

**Comment by basalona** [comment]
I am getting this error whichever files I try, and all the English sources
are selected with 4K and 1080P sorting.

**Comment by davidreedmichigan** [comment]
From RD doc, the  503 error is: **Service unavailable** 
Do you still have the issue? 
Check your account on RD to see if you don't have any issue and let me know

**Comment by basalona** [comment]
I can use RD without any issue in any other form apart from Helios. I think
this issue started with the latest addon update from Helios. Is there any
way to downgrade it?

**Comment by basalona** [comment]
I figured it out. The culprit is the new Guardian VPN app. It is blocking
the Helios search for files for some reason. Rest all functionality in Wako
app is fine with the VPN enabled. Is there any way you can fix it?

**Comment by davidreedmichigan** [comment]
Do you know what URL it blocks exactly? 
I don't really know how to change this especially if it blocks RD API call.

**Comment by basalona** [comment]
Looks like they are blocking the  RD API call. If its too much trouble,
just ignore it- I will disconnect the VPN while searching for the sources.
