### ISSUE TITLE
TV Shows pack-Debrid- plays the first episode alone

### ISSUE THREAD

**Issue by onlytanmoy** [wako-unofficial-addons/helios#19]
Please refer attached screenshot. After searching for a file in Helios., when I click on these Debrid links and select 'play in kodi', it just plays the first episode.
There is no option to play the next episode.
I don't even get a pop-up asking me to select episode I want to play. Happens with debrid links alone. Pls fix this.
![Screenshot_20190917-192435_wako](https://user-images.githubusercontent.com/48493659/65177670-128cce00-da4f-11e9-8552-facc593c82d4.png)

**Comment by davidreedmichigan** [comment]
false alert, it's RD issue
