### ISSUE TITLE
Bug: doesn't play right episode in pack 

### ISSUE THREAD

**Issue by Crapy** [wako-unofficial-addons/helios#27]
I have had it in a lot of shows, where I play stream from a pack and it usually plays the first episode of the season instead of the episode I wanna play

For example 

Friends s09 complete pack stream will always play only s09e01 no matter what episode I am currently at

**Comment by davidreedmichigan** [comment]
Do you still encounter this issue?

**Comment by Crapy** [comment]
> Do you still encounter this issue?

Nope!
