### ISSUE TITLE
REQUEST: Use Original Title When Scraping and Ability to Use Torrent Files Instead of Magnet when Scraping 

### ISSUE THREAD

**Issue by MadMax96xaMdaM** [wako-unofficial-addons/helios#29]
Original names often matters for foreign stuff on foreign websites and the ability to use torrent files instead of magnets would be helpful for some websites that don't have magnets.

I realize these features might not matter a lot of people but I am just putting them out there because it would be nice to have them IF they would be easy to add or maybe sometime in the future. If they would require a lot of work I understand that they are not that important.

**Comment by davidreedmichigan** [comment]
Could you do a try and use `{title.original}` instead of `{title}` in the providers you use and let me know if this is more accurate. 
Helios already woks with torrent file, magnet are only used for debrid service.

**Comment by davidreedmichigan** [comment]
Option has been added
