### ISSUE TITLE
Request: Let us filter file size

### ISSUE THREAD

**Issue by oathzed** [wako-unofficial-addons/helios#33]
Let us filter if something is below a certain size and above a certain size.

This can be tricky for season packs.

For math, if title contains "S03" or "Season 3 -" with no "E0", then probably a season pack, so get episode number inside season then divide it by file size, to get the average size per episode. then you would take this into account with what size you're filter out.

If contains every season, look for "S01-S07" so if includes total number of seasons of show, then you can assume its every season, so divide number of episodes in total show with file size of pack to find average episode size.

**Comment by davidreedmichigan** [comment]
done
