### ISSUE TITLE
Bug: Seeds/leaches color coded wrong

### ISSUE THREAD

**Issue by oathzed** [wako-unofficial-addons/helios#36]
I see some things having seeds that say "S: 39 / L: 30" it will be green, and that's fine. but one below it, will be "S: 49 / L: 60" and be yellow, why is something with more seeds being color coded yellow?

**Comment by davidreedmichigan** [comment]
Sorry for the late answer, I missed your issue. Green if S > L, Yellow if S < L, Red if not a lot S
