### ISSUE TITLE
Request: add support for nested api calls

### ISSUE THREAD

**Issue by mkavidas** [wako-unofficial-addons/helios#38]
I am trying to make a provider for Emby but the problem is it takes two API calls to get the data.

First you have to search for the item to get the itemID then you have to make an api call to get a stream using the item id. 

For example:
    `curl -X GET "http://127.0.0.1:8096/emby/Items?Recursive=true&AnyProviderIdEquals=imdb.tt0099939&api_key=644881774e2b41e1bdf6e3c341c4fe31" -H         "accept: "application/json"`

response:
```
{
  "Items": [
    {
      "Name": "King of New York",
      "ServerId": "db7464b259f748fcb9029a21f8asd123",
      "Id": "184837",
      "PremiereDate": "1990-07-18T04:00:00.0000000+00:00",
      "OfficialRating": "R",
      "CommunityRating": 6.7,
      "RunTimeTicks": 61914460160,
      "ProductionYear": 1990,
      "IsFolder": false,
      "Type": "Movie",
      "ImageTags": {
        "Primary": "44ef33a46b08c48c0fcd5140e6ca07f2",
        "Logo": "a0fd4b8e7542ac3b0b771a9509f19509",
        "Thumb": "2d8f0890ebf64313c042a0e756941bb3"
      },
      "BackdropImageTags": [
        "7a5bbb0fac2cc8a626af6caaaee06a78"
      ],
      "MediaType": "Video"
    }
  ],
  "TotalRecordCount": 1
}
```
then you can use /videos/id/stream to get the video stream

**Comment by davidreedmichigan** [comment]
There is a subpage property to do, but today provider system works only with torrents, need to update this to be able to pass a stream link instead

**Comment by mkavidas** [comment]
What changes would be needed to make that work. I am willing to do the development for this but I want to make sure my implementation is consistent with how the devs want it done. This would also solve issue #23 and #37 .

Technically it already supports stream links (streamLinkSources) but only from RD/PM. Basically we add a type flag to the provider (torrent/stream) and based on that flag either check RD/PM or just send the link directly to the desired player (quick and dirty way). Or we could refactor the provider interface to have a base interface and torrent/direct that inherit from base each with their own extra information (seeds,peers). 

Haven't done NodeJS development in a while so not sure what the best way to go about this would be.
