### ISSUE TITLE
[REQUEST] Additional Replacement Keywords

### ISSUE THREAD

**Issue by orionoidx** [wako-unofficial-addons/helios#56]
Maybe I’m wrong, but when I worked through the Helios code it seems that only "imdbId" is replaced in the provider query string. Is there anyway the Trakt/TMDb/TVDb IDs can also be added to the query string if they are available (for both movies and episodes)?

When querying episodes, the "imdbId" seems to be null with most episodes. I think that the episode’s IMDb ID is used (which is not available for a lot of them). Is there any way the **show’s** IDs can also be added to the query string? This is useful if you want to create a query with the show IMDb ID and the season/episode number. You will then have something like this query:

`idmd={imdbIdShow}&trakt={traktIdShow}&season={season}&episode={episode}`

or using the **episode’s** ID instead of the show’s ID:

`idmd={imdbIdEpisode}&trakt={traktIdEpisode}`

**Comment by davidreedmichigan** [comment]
Added more ids: 
https://github.com/wako-unofficial-addons/helios/commit/32ef052cf42ef9a5c27d11ee9fad7fc8e2fbe981#diff-52e56bf24e4eb1dee2cdf7f5bd98469fR330

**Comment by orionoidx** [comment]
Thanks for adding this so quickly. There are still some problems.

Firstly the episode metadata in the developer version (episode.page.ts) does not seem to work anymore. Scraping the test episode throws this exception:

```
core.js:4061 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'toString' of undefined
TypeError: Cannot read property 'toString' of undefined
    at add0 (tools.ts:43)
    at getSourceQueryEpisode (tools.ts:285)
    at Function.push../projects/plugin/src/plugin/queries/source-query-from-kodi-open-media.query.ts.SourceQueryFromKodiOpenMediaQuery.getData (source-query-from-kodi-open-media.query.ts:17)
    at SearchSourceComponent.<anonymous> (search-source.component.ts:49)
```

It seems that the metadata episode.page.ts does not match what is expected in the Helios code. For instance, Helios is looking for:

```
episode.ids.imdb
episode.seasonNumber
```

But the hardcoded metadata contains a different structure:

```
imdbId
traktSeasonNumber
```

Secondly, since this exception is thrown, I cannot test the new code, but the **show IMDb ID** still seems to be missing. You now have:

```
  sourceEpisodeQuery.showTvdbId = show.ids.tvdb;
  sourceEpisodeQuery.showTraktId = show.ids.trakt;
  sourceEpisodeQuery.showTmdbId = show.ids.tmdb;
  sourceEpisodeQuery.showSimklId = show.ids.simkl;
```

Any reason why the IMDb ID of the show was not added?

**Comment by davidreedmichigan** [comment]
wako's sdk has been updated with a lot of change in their entities. In the `episode.page.ts` it sill uses old structure hence the error, but doesn't happen in production mode.
I'll add imdb Id for the show.

**Comment by orionoidx** [comment]
Still not working. The show's IMDb is not propagating through the code.

You forgot to add the following to `tools.js` within the `getSourceQueryEpisode` function:

`sourceEpisodeQuery.showImdbId = show.ids.imdb;`

**Comment by orionoidx** [comment]
And should the IMDb ID in` source-query.ts` not be a string?

From this:

`showImdbId: number;`

to this:

`showImdbId: string;`

**Comment by davidreedmichigan** [comment]
All fixed. Feel free to open a PR, it helps us a lot
