### ISSUE TITLE
trust_results for Episodes

### ISSUE THREAD

**Issue by orionoidx** [wako-unofficial-addons/helios#58]
I noticed you added the "trust_results" attribute for providers, thanks for that. However, this is **only** used for movies. Any reason why this cannot be applied to episodes as well? The reason for this is that Helios has a very limited season/episode detection for filenames. If the filename contains uncommon season/episode numbering, foreign names\labels, or anything that is slightly off, Helios removes those links. During testing about 80% of all episode links are removed for no good reason (eg: containing Russian/French labels, season packs that contain multiple seasons instead of just one, or filenames that contain encoding labels like "S83" which is then confused as the incorrect season number).

Would it be possible to bypass Helio's filename detection for episodes as well:

1. In `torrents-from-provider-base.query.ts` change this:
`if (provider.trust_results === true && sourceQuery.movie)`
to this:
`if (provider.trust_results === true)`

2. In the `removeBadTorrents` function you check if this is an episode or season pack. Would it be possible for the provider to specify if the results are a pack or not (instead of trying to detect it from the filename)? Providers could then specify in their JSON format to contain a pack boolean attribute (see last line below), eg:
```
"json_format": {
      "results": "data.movies",
      "sub_results": "torrents",
      "url": "url",
      "title": "title_long",
      "seeds": "seeds",
      "peers": "peers",
      "size": "size_bytes",
      "quality": "quality",
      "pack": "pack"
}
```
And then `removeBadTorrents` is only called if the provider did not specify the "trust_results" attribute. I haven't seen any of the other torrent providers use "trust_results", so these changes should not impact the quality of results returned by them..

**Comment by davidreedmichigan** [comment]
Check this https://github.com/wako-unofficial-addons/helios/commit/e06a3f5ff5d0407a6c85676a28dc8f5605f712c0#diff-3bc471e56468bdf79d9b973cd1eee931R34

**Comment by orionoidx** [comment]
Thanks for the changes. `trust_results` works now. However the `isPackage` is still detected in `removeBadTorrents() `which is now skipped due to `trust_results`. I took the liberty of creating a PR for adding `isPackage` as an attribute to the provider, so providers can set it themselves instead of letting Helios detect it from the filename. Would appreciate it if you could merge the request.

Pull request: #61
