### ISSUE TITLE
Option to bookmark search results under search source manually

### ISSUE THREAD

**Issue by onlytanmoy** [wako-unofficial-addons/helios#7]
In Movies & TV Shows sections, for 'Search Source Manually' feature, please provide an option to bookmark the search results so that I can access all such bookmarked results at a later time without having to trigger the same manual search and more importantly scroll through all search results to find that particular stream.
This becomes greatly helpful when a show has got several episodes, where each day I plan to watch one episode from a specific "working" link.
You can create a section like 'Manual Bookmarks' under Helios to implement this feature.

**Comment by davidreedmichigan** [comment]
Unfortunately this is not something I will do in the near future, I closing it until
