### ISSUE TITLE
Hi Sir,can you re add the cached torrents to their cached server?

### ISSUE THREAD

**Issue by brmnh123456** [wako-unofficial-addons/helios#8]
Although I can know a torrent is cached or not,but when it is cached,I even can not find its magnet link,so i can not re add it to its cached server.And I can not view it in pd or rd kodi addon(both linked to my pm and rd account).If we can re add the cached torrents to the cloud,next time we could easily find them in the cloud addon,no need to re search wako or seren.

**Comment by brmnh123456** [comment]
Sir,can you make some change that the cached torrents can general its magnet link,or the cached torrent can just be download?Thank you Sir.

**Comment by davidreedmichigan** [comment]
This has been fixed
